### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by AdarshRevankar** [shubham298/flask-gain-app#1]
### There are few changes required in the design

![Annotation 2020-04-27 210103](https://user-images.githubusercontent.com/48080453/80391664-aa974380-88cb-11ea-811f-94b0d934482c.jpg)

- [x] **Button** `onClick="generateImage( )"` inside the window
- [x] A **view to show the Generated image** ( either on the Click / Static )
- [x] **Texture Indication** of the Color ( Eg: Tree should be written on the green color )
- [x] Add a new Horizontal / Vertical Toolbar / On the Right side add the **Style Images**
- [x] Removal of **Rectangle, Triangle, Line & Eraser** tool
- [x] **Header Section** - Write our project name( Optional )

**Comment by shubham298** [comment]
Added almost all changes and successfully connected backend and front-end

**Comment by AdarshRevankar** [comment]
- [x] Please do remove the file name **Edit Text** below the semantic image
- [x] Add the **Time Stamp** (Unix timestamp) as the filename and `.png` at the end

**Comment by shubham298** [comment]
Added Vertical Toolbar (styled images), timestamp, improve CSS.

**Comment by shubham298** [comment]
Done with texture Indication
